//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetVault {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetVault.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VaultSafe types should be vault-safe..
        /// </summary>
        public static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; is annotated with the VaultSafe attribute but is not provably vault-safe.
        /// </summary>
        public static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types annotated with the VaultSafe attribute must be vault-safe.
        /// </summary>
        public static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections.Immutable.ImmutableHashSet`1;
        ///System.Collections.Immutable.ImmutableList`1+Enumerator;
        ///System.Collections.Immutable.ImmutableQueue`1+Enumerator;
        ///System.Collections.Immutable.ImmutableArray`1+Enumerator;
        ///System.Collections.Immutable.ImmutableHashSet`1+Enumerator;
        ///System.Collections.Immutable.ImmutableSortedSet`1;
        ///System.Collections.Immutable.ImmutableDictionary`2+Enumerator;
        ///System.Collections.Immutable.ImmutableSortedDictionary`2+Enumerator;
        ///System.Collections.Immutable.ImmutableL [rest of string was truncated]&quot;;.
        /// </summary>
        public static string condit_generic_whitelist {
            get {
                return ResourceManager.GetString("condit_generic_whitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String;  System.Uri;.
        /// </summary>
        public static string VaultSafeWhiteList {
            get {
                return ResourceManager.GetString("VaultSafeWhiteList", resourceCulture);
            }
        }
    }
}
