//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetVault.Test.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Bug62TestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bug62TestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetVault.Test.ResourceFiles.Bug62TestCases", typeof(Bug62TestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Immutable;
        ///using System.Text;
        ///using DotNetVault.Attributes;
        ///using JetBrains.Annotations;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [NoNonVsCapture]
        ///    public delegate TResult LocalQuery&lt;TInput, [VaultSafeTypeParam] TResult&gt;(in TInput input);
        ///
        ///    [NoNonVsCapture]
        ///    public delegate TResult LocalQuery&lt;TInput, [VaultSafeTypeParam] TAncillary, [VaultSafeTypeParam] TResult&gt;(
        ///        in TInput input, in TAncillary ancillary);
        ///
        ///    [NoNonVsCapture]
        ///    pu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bug62NotWorkingTestCase {
            get {
                return ResourceManager.GetString("Bug62NotWorkingTestCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Immutable;
        ///using System.Text;
        ///using DotNetVault.Attributes;
        ///using JetBrains.Annotations;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [NoNonVsCapture]
        ///    public delegate TResult LocalQuery&lt;TInput, [VaultSafeTypeParam] TResult&gt;(in TInput input);
        ///
        ///    [NoNonVsCapture]
        ///    public delegate TResult LocalQuery&lt;TInput, [VaultSafeTypeParam] TAncillary, [VaultSafeTypeParam] TResult&gt;(
        ///        in TInput input, in TAncillary ancillary);
        ///
        ///    [NoNonVsCapture]
        ///    pu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bug62TestCaseOneCurrentlyWorks {
            get {
                return ResourceManager.GetString("Bug62TestCaseOneCurrentlyWorks", resourceCulture);
            }
        }
    }
}
