//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetVault.Test.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Bug64TestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bug64TestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetVault.Test.ResourceFiles.Bug64TestCases", typeof(Bug64TestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.Attributes;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [VaultSafe]
        ///    public struct Bug64Demo
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Should NOT need to comment out setter to compile (and currently do not)
        ///        /// &lt;/summary&gt;
        ///        public DateTime Timestamp
        ///        {
        ///            get; 
        ///            set;
        ///        }
        ///
        ///        /// &lt;summary&gt;
        ///        /// Should NOT need to comment out  setter to compile (but currently do)
        ///        /// &lt;/summary&gt;
        ///        publi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bug64Demo_ShouldCompile_1 {
            get {
                return ResourceManager.GetString("Bug64Demo_ShouldCompile_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.Attributes;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [VaultSafe]
        ///    public sealed class Bug64DemoCounterpoint1
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Should need to comment out set to compile
        ///        /// (Currently works correctly)
        ///        /// &lt;/summary&gt;
        ///        public DateTime TimeStamp
        ///        {
        ///            get;
        ///            //set;
        ///        }
        ///
        ///        /// &lt;summary&gt;
        ///        /// Should need to comment out set to compile
        ///        /// (Currently works corr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bug64Demo_ShouldCompile_2 {
            get {
                return ResourceManager.GetString("Bug64Demo_ShouldCompile_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Text;
        ///using DotNetVault.Attributes;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [VaultSafe]
        ///    struct Bug64DemoShouldNotCompile
        ///    {
        ///        public DateTime TimeStamp { get; set; }
        ///
        ///        public StringBuilder StatusText { get; }
        ///
        ///        public Bug64DemoShouldNotCompile(DateTime ts, string text)
        ///        {
        ///            TimeStamp = ts;
        ///            StatusText = new StringBuilder(text);
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Bug64Demo_ShouldNotCompile_1 {
            get {
                return ResourceManager.GetString("Bug64Demo_ShouldNotCompile_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using DotNetVault.Attributes;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [VaultSafe]
        ///    public sealed class Bug64DemoCounterpoint2
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Should need to comment out set to compile
        ///        /// (Currently works correctly)
        ///        /// &lt;/summary&gt;
        ///        public DateTime TimeStamp
        ///        {
        ///            get;
        ///            set;
        ///        }
        ///
        ///        /// &lt;summary&gt;
        ///        /// Should need to comment  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bug64Demo_ShouldNotCompile_2 {
            get {
                return ResourceManager.GetString("Bug64Demo_ShouldNotCompile_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.Attributes;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [VaultSafe]
        ///    public sealed class Bug64DemoCounterpoint
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Should need to comment out set to compile
        ///        /// (Currently works correctly)
        ///        /// &lt;/summary&gt;
        ///        public DateTime TimeStamp
        ///        {
        ///            get;
        ///            set;
        ///        }
        ///
        ///        /// &lt;summary&gt;
        ///        /// Should need to comment out set to compile
        ///        /// (Currently works correct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bug64Demo_ShouldNotCompile_3 {
            get {
                return ResourceManager.GetString("Bug64Demo_ShouldNotCompile_3", resourceCulture);
            }
        }
    }
}
