//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetVault.Test.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Bug76TestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bug76TestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetVault.Test.ResourceFiles.Bug76TestCases", typeof(Bug76TestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Text;
        ///using DotNetVault.Attributes;
        ///using JetBrains.Annotations;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Execute a potentially mutating action on the vault
        ///    /// &lt;/summary&gt;
        ///    /// &lt;typeparam name=&quot;TResource&quot;&gt;the type of protected resource you wish to mutate&lt;/typeparam&gt;
        ///    /// &lt;typeparam name=&quot;TAncillary&quot;&gt;an ancillary type used in the delegate.  must be vault safe, must be passed
        ///    /// by readonly-reference.&lt;/typeparam&gt;
        ///    /// &lt;param name=&quot;res&quot;&gt;the pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bug76TestCase1 {
            get {
                return ResourceManager.GetString("Bug76TestCase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Text;
        ///using DotNetVault.Attributes;
        ///using JetBrains.Annotations;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Execute a potentially mutating action on the vault
        ///    /// &lt;/summary&gt;
        ///    /// &lt;typeparam name=&quot;TResource&quot;&gt;the type of protected resource you wish to mutate&lt;/typeparam&gt;
        ///    /// &lt;typeparam name=&quot;TAncillary&quot;&gt;an ancillary type used in the delegate.  must be vault safe, must be passed
        ///    /// by readonly-reference.&lt;/typeparam&gt;
        ///    /// &lt;param name=&quot;res&quot;&gt;the pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bug76TestCase2 {
            get {
                return ResourceManager.GetString("Bug76TestCase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Text;
        ///using DotNetVault.Attributes;
        ///using JetBrains.Annotations;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Execute a potentially mutating action on the vault
        ///    /// &lt;/summary&gt;
        ///    /// &lt;typeparam name=&quot;TResource&quot;&gt;the type of protected resource you wish to mutate&lt;/typeparam&gt;
        ///    /// &lt;typeparam name=&quot;TAncillary&quot;&gt;an ancillary type used in the delegate.  must be vault safe, must be passed
        ///    /// by readonly-reference.&lt;/typeparam&gt;
        ///    /// &lt;param name=&quot;res&quot;&gt;the pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bug76TestCase3 {
            get {
                return ResourceManager.GetString("Bug76TestCase3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Text;
        ///using DotNetVault.Attributes;
        ///using JetBrains.Annotations;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Execute a potentially mutating action on the vault
        ///    /// &lt;/summary&gt;
        ///    /// &lt;typeparam name=&quot;TResource&quot;&gt;the type of protected resource you wish to mutate&lt;/typeparam&gt;
        ///    /// &lt;typeparam name=&quot;TAncillary&quot;&gt;an ancillary type used in the delegate.  must be vault safe, must be passed
        ///    /// by readonly-reference.&lt;/typeparam&gt;
        ///    /// &lt;param name=&quot;res&quot;&gt;the pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bug76TestCase4 {
            get {
                return ResourceManager.GetString("Bug76TestCase4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Text;
        ///using DotNetVault.Attributes;
        ///using JetBrains.Annotations;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Execute a potentially mutating action on the vault
        ///    /// &lt;/summary&gt;
        ///    /// &lt;typeparam name=&quot;TResource&quot;&gt;the type of protected resource you wish to mutate&lt;/typeparam&gt;
        ///    /// &lt;typeparam name=&quot;TAncillary&quot;&gt;an ancillary type used in the delegate.  must be vault safe, must be passed
        ///    /// by readonly-reference.&lt;/typeparam&gt;
        ///    /// &lt;param name=&quot;res&quot;&gt;the pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bug76TestCase5 {
            get {
                return ResourceManager.GetString("Bug76TestCase5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Text;
        ///using DotNetVault.Attributes;
        ///using JetBrains.Annotations;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Execute a potentially mutating action on the vault
        ///    /// &lt;/summary&gt;
        ///    /// &lt;typeparam name=&quot;TResource&quot;&gt;the type of protected resource you wish to mutate&lt;/typeparam&gt;
        ///    /// &lt;typeparam name=&quot;TAncillary&quot;&gt;an ancillary type used in the delegate.  must be vault safe, must be passed
        ///    /// by readonly-reference.&lt;/typeparam&gt;
        ///    /// &lt;param name=&quot;res&quot;&gt;the pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bug76TestCase6 {
            get {
                return ResourceManager.GetString("Bug76TestCase6", resourceCulture);
            }
        }
    }
}
