//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetVault.Test.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BvIllegalRefExprTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BvIllegalRefExprTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetVault.Test.ResourceFiles.BvIllegalRefExprTestCases", typeof(BvIllegalRefExprTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.Attributes;
        ///using DotNetVault.Vaults;
        ///using JetBrains.Annotations;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [VaultSafe]
        ///    public struct BvIllegalRefExprTestCase1
        ///    {
        ///        
        ///        public DateTime TimeStamp { get; set; }
        ///
        ///        [NotNull]
        ///        public string Name
        ///        {
        ///            get =&gt; _name ??= string.Empty;
        ///            set =&gt; _name = value ?? throw new ArgumentNullException(nameof(value));
        ///        }
        ///
        ///        public BvIllegalRefExprTestC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BvIllegalRefExprTestCase1 {
            get {
                return ResourceManager.GetString("BvIllegalRefExprTestCase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.Attributes;
        ///using DotNetVault.Vaults;
        ///using JetBrains.Annotations;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [VaultSafe]
        ///    public struct BvIllegalRefExprTestCase2
        ///    {
        ///        public DateTime TimeStamp { get; set; }
        ///
        ///        [NotNull]
        ///        public string Name
        ///        {
        ///            get =&gt; _name ??= string.Empty;
        ///            set =&gt; _name = value ?? throw new ArgumentNullException(nameof(value));
        ///        }
        ///
        ///        public BvIllegalRefExprTestCase2([NotN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BvIllegalRefExprTestCase2 {
            get {
                return ResourceManager.GetString("BvIllegalRefExprTestCase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.Attributes;
        ///using DotNetVault.Vaults;
        ///using JetBrains.Annotations;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [VaultSafe]
        ///    public struct BvIllegalRefExprTestCase2
        ///    {
        ///        public DateTime TimeStamp { get; set; }
        ///
        ///        [NotNull]
        ///        public string Name
        ///        {
        ///            get =&gt; _name ??= string.Empty;
        ///            set =&gt; _name = value ?? throw new ArgumentNullException(nameof(value));
        ///        }
        ///
        ///        public BvIllegalRefExprTestCase2([NotN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BvIllegalRefExprTestCase3 {
            get {
                return ResourceManager.GetString("BvIllegalRefExprTestCase3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.Attributes;
        ///using DotNetVault.Vaults;
        ///using JetBrains.Annotations;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [VaultSafe]
        ///    public struct BvIllegalRefExprTestCase2
        ///    {
        ///        public DateTime TimeStamp { get; set; }
        ///
        ///        [NotNull]
        ///        public string Name
        ///        {
        ///            get =&gt; _name ??= string.Empty;
        ///            set =&gt; _name = value ?? throw new ArgumentNullException(nameof(value));
        ///        }
        ///
        ///        public BvIllegalRefExprTestCase2([NotN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BvIllegalRefExprTestCase4 {
            get {
                return ResourceManager.GetString("BvIllegalRefExprTestCase4", resourceCulture);
            }
        }
    }
}
