//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetVault.Test.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CopyAssignmentTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CopyAssignmentTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetVault.Test.ResourceFiles.CopyAssignmentTestCases", typeof(CopyAssignmentTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Diagnostics.CodeAnalysis;
        ///using System.Text;
        ///using DotNetVault.Attributes;
        ///using DotNetVault.Vaults;
        ///using Rwlkres = DotNetVault.LockedResources.RwLockedResource&lt;DotNetVault.Vaults.BasicReadWriteVault&lt;DotNetVault.Test.TestCases.MutableStructExample&gt;, DotNetVault.Test.TestCases.MutableStructExample&gt;;
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    static class CopyAssignmentTests
        ///    {
        ///        public static void ReadWriteAccess()
        ///        {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CopyAssignmentTestCase1 {
            get {
                return ResourceManager.GetString("CopyAssignmentTestCase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Diagnostics.CodeAnalysis;
        ///using System.Text;
        ///using DotNetVault.Attributes;
        ///using DotNetVault.Vaults;
        ///using Rwlkres = DotNetVault.LockedResources.RwLockedResource&lt;DotNetVault.Vaults.BasicReadWriteVault&lt;DotNetVault.Test.TestCases.MutableStructExample&gt;, DotNetVault.Test.TestCases.MutableStructExample&gt;;
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    static class CopyAssignmentTests
        ///    {
        ///        public static void ReadWriteAccess()
        ///        {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CopyAssignmentTestCase2 {
            get {
                return ResourceManager.GetString("CopyAssignmentTestCase2", resourceCulture);
            }
        }
    }
}
