//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetVault.Test.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EarlyReleaseTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EarlyReleaseTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetVault.Test.ResourceFiles.EarlyReleaseTestCases", typeof(EarlyReleaseTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.Attributes;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public sealed class EarlyReleaseMethodHaver : IDisposable
        ///    {
        ///        public string Text { get; } = &quot;Some text&quot;;
        ///        [EarlyRelease]
        ///        public void ReleaseEarly() { Console.WriteLine(@&quot;Releasing early.&quot;); }
        ///
        ///        public void Dispose()
        ///        {
        ///
        ///        }
        ///    }
        ///
        ///    public static class TestFindEarlyReleaseAttribute
        ///    {
        ///        [return : UsingMandatory]
        ///        [EarlyReleaseJustification [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EarlyReleaseErrorCaseHaver {
            get {
                return ResourceManager.GetString("EarlyReleaseErrorCaseHaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.Attributes;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public sealed class EarlyReleaseMethodHaver : IDisposable
        ///    {
        ///        public string Text { get; } = &quot;Some text&quot;;
        ///        [EarlyRelease]
        ///        public void ReleaseEarly() { Console.WriteLine(@&quot;Releasing early.&quot;); }
        ///
        ///        public void Dispose()
        ///        {
        ///
        ///        }
        ///    }
        ///
        ///    public static class TestFindEarlyReleaseAttribute
        ///    {
        ///        [return: UsingMandatory]
        ///        [EarlyReleaseJustification( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestEarlyReleaseBadJustification {
            get {
                return ResourceManager.GetString("TestEarlyReleaseBadJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using DotNetVault.Attributes;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public sealed class EarlyReleaseMethodHaver : IDisposable
        ///    {
        ///        [EarlyRelease]
        ///        public void ReleaseEarly() { Console.WriteLine(@&quot;Releasing early.&quot;);}
        ///
        ///        public void Dispose()
        ///        {
        ///
        ///        }
        ///    }
        ///
        ///    public static class TestFindEarlyReleaseAttribute
        ///    {
        ///        [EarlyReleaseJustification(EarlyReleaseReason.CustomWrapper [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestFindEarlyReleaseAttribute {
            get {
                return ResourceManager.GetString("TestFindEarlyReleaseAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.Attributes;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public sealed class EarlyReleaseMethodHaver : IDisposable
        ///    {
        ///        public string Text { get; } = &quot;Some text&quot;;
        ///        [EarlyRelease]
        ///        public void ReleaseEarly() { Console.WriteLine(@&quot;Releasing early.&quot;); }
        ///
        ///        public void Dispose()
        ///        {
        ///
        ///        }
        ///    }
        ///
        ///    public static class TestFindEarlyReleaseAttribute
        ///    {
        ///        [return: UsingMandatory]
        ///        public static EarlyReleaseM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnjustifiedEarlyRelease {
            get {
                return ResourceManager.GetString("UnjustifiedEarlyRelease", resourceCulture);
            }
        }
    }
}
