//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetVault.Test.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Issue8TestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Issue8TestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetVault.Test.ResourceFiles.Issue8TestCases", typeof(Issue8TestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.Attributes;
        ///using JetBrains.Annotations;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public enum TestCaseMode
        ///    {
        ///        NotWorking = 0,
        ///        Working
        ///    }
        ///
        ///    [VaultSafe]
        ///    public sealed class Issue8TestCase
        ///    {
        ///        [NotNull] public string FirstName { get;  }
        ///
        ///        [NotNull] public string LastName { get; }
        ///
        ///        public TestCaseMode? Mode { get; }
        ///
        ///        public Issue8TestCase([NotNull] string firstName, string lastName)
        ///        {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Issue8_TestCases {
            get {
                return ResourceManager.GetString("Issue8_TestCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using DotNetVault.Attributes;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [VaultSafe]
        ///    struct Issue8TestCase2Similar
        ///    {
        ///        public int X;
        ///        public int Y;
        ///        public int Z;
        ///
        ///        public Issue8TestCase2Similar(int x, int y, int z)
        ///        {
        ///            X = x;
        ///            Y = y;
        ///            Z = z;
        ///        }
        ///    }
        ///
        ///    [VaultSafe]
        ///    public sealed class TestMe
        ///    {
        ///        public TestMe(int x, in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Issue8TestCase2Similar {
            get {
                return ResourceManager.GetString("Issue8TestCase2Similar", resourceCulture);
            }
        }
    }
}
