//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetVault.Test.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NdiTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NdiTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetVault.Test.ResourceFiles.NdiTestCases", typeof(NdiTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using DotNetVault.Attributes;
        ///using JetBrains.Annotations;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [NoCopy]
        ///    public readonly ref struct NoCopyAttributeWithBadAssignment
        ///    {
        ///        [return: UsingMandatory]
        ///        public static NoCopyAttributeWithBadAssignment CreateValue([NotNull] string s) =&gt;
        ///            new NoCopyAttributeWithBadAssignment(s);
        ///        public string Name =&gt; _name ?? string.Empty;
        ///
        ///        public vo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtensionMethodPbvTest {
            get {
                return ResourceManager.GetString("ExtensionMethodPbvTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.Vaults;
        ///using RwLck = DotNetVault.CustomVaultExamples.CustomLockedResources.StringBuilderRwLockedResource;
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public ref struct IllegalWrapper
        ///    {
        ///        public static IllegalWrapper CreateCopyInSneakyWay(in RwLck lck, DateTime ts) =&gt; new IllegalWrapper(in lck, ts);
        ///
        ///        public RwLck WrappedLockedResource;
        ///        public DateTime Ts;
        ///
        ///        public void SetLockedResource(in RwLck lck) =&gt; WrappedLockedResource = lck;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IllegalWrapperTestCase {
            get {
                return ResourceManager.GetString("IllegalWrapperTestCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.Vaults;
        ///using RwLck = DotNetVault.CustomVaultExamples.CustomLockedResources.StringBuilderRwLockedResource;
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public ref struct IllegalWrapper
        ///    {
        ///        public static IllegalWrapper CreateCopyInSneakyWay(in RwLck lck, DateTime ts) =&gt; new IllegalWrapper(in lck, ts);
        ///
        ///        public RwLck WrappedLockedResource;
        ///        public DateTime Ts;
        ///
        ///        public void SetLockedResource(in RwLck lck) =&gt; WrappedLockedResource = lck;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string illegalwrappertestcase2 {
            get {
                return ResourceManager.GetString("illegalwrappertestcase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.Vaults;
        ///using RwLock = DotNetVault.CustomVaultExamples.CustomLockedResources.StringBuilderRwLockedResource;
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    ref struct RwLockWrapper
        ///    {
        ///        public RwLock WrappedLock { get; }
        ///        public string Name { get; }
        ///
        ///        public RwLockWrapper(in RwLock lck, string text)
        ///        {
        ///            WrappedLock = lck;
        ///            Name = text ?? string.Empty;
        ///        }
        ///
        ///        public new readonly string ToString() =&gt; Wra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string illegalwrappertestcase3 {
            get {
                return ResourceManager.GetString("illegalwrappertestcase3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Text;
        ///using DotNetVault.CustomVaultExamples.CustomLockedResources;
        ///using DotNetVault.Vaults;
        ///using RoLock = DotNetVault.CustomVaultExamples.CustomLockedResources.StringBuilderRoLockedResource;
        ///using UpRoLock = DotNetVault.CustomVaultExamples.CustomLockedResources.StringBuilderUpgradableRoLockedResource;
        ///using RwLock = DotNetVault.CustomVaultExamples.CustomLockedResources.StringBuilderRwLockedResource;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///
        ///
        ///    static class IllegalWr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IllegalWrapperTestCase4 {
            get {
                return ResourceManager.GetString("IllegalWrapperTestCase4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.TestCaseHelpers;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    static class NdiMixedWithNotInlineNotOkCaseThree
        ///    {
        ///        public static void NotOkNdiAndNotOkNotInlineTest()
        ///        {
        ///            Name chris;
        ///            using (chris = Name.CreateName(&quot;chris&quot;))
        ///            {
        ///                Console.WriteLine(chris.Text);
        ///            }
        ///            chris.Dispose();
        ///            Console.WriteLine(chris.Text);
        ///
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string NdiMixedWithNotInlineNotOkCaseThree {
            get {
                return ResourceManager.GetString("NdiMixedWithNotInlineNotOkCaseThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.TestCaseHelpers;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    static class NdiNotOkCaseOne
        ///    {
        ///        public static void NotOkNdiTest()
        ///        {
        ///            using var chris = Name.CreateName(&quot;chris&quot;);
        ///            chris.Dispose();
        ///            Console.WriteLine(chris.Text);
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string NdiNotOkCaseOne {
            get {
                return ResourceManager.GetString("NdiNotOkCaseOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.TestCaseHelpers;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    static class NdiNotOkCaseTwo
        ///    {
        ///        public static void NotOkNdiTest()
        ///        {
        ///            using (var chris = Name.CreateName(&quot;chris&quot;))
        ///            {
        ///                Console.WriteLine(chris.Text);
        ///                chris.Dispose();
        ///                Console.WriteLine(chris.Text);
        ///            }
        ///            
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string NdiNotOkTestTwo {
            get {
                return ResourceManager.GetString("NdiNotOkTestTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using DotNetVault.Attributes;
        ///using JetBrains.Annotations;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [NoCopy]
        ///    public readonly ref struct NoCopyAttributeWithBadAssignment
        ///    {
        ///        [return: UsingMandatory]
        ///        public static NoCopyAttributeWithBadAssignment CreateValue([NotNull] string s) =&gt;
        ///            new NoCopyAttributeWithBadAssignment(s);
        ///        public string Name =&gt; _name ?? string.Empty;
        ///
        ///        public vo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoCopyAttributeWithBadAssignment {
            get {
                return ResourceManager.GetString("NoCopyAttributeWithBadAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.Attributes;
        ///using JetBrains.Annotations;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [NoCopy]
        ///    public readonly ref struct NoCopyAttributeWithBadAssignment
        ///    {
        ///        [return: UsingMandatory]
        ///        public static NoCopyAttributeWithBadAssignment CreateValue([NotNull] string s) =&gt;
        ///            new NoCopyAttributeWithBadAssignment(s);
        ///        public string Name =&gt; _name ?? string.Empty;
        ///        public new string ToString() =&gt; Name;
        ///        public void Dispose [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoCopyBadAssignUsingStatement {
            get {
                return ResourceManager.GetString("NoCopyBadAssignUsingStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.Vaults;
        ///using RwLck = DotNetVault.CustomVaultExamples.CustomLockedResources.StringBuilderRwLockedResource;
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public readonly ref struct FinalBadWrapper
        ///    {
        ///        public RwLck Lock =&gt; _rwLck;
        ///        public DateTime Stamp =&gt; _ts;
        ///        public string Text =&gt; _text ?? &quot;NONE&quot;;
        ///
        ///        internal FinalBadWrapper(in RwLck lck, string text)
        ///        {
        ///            _rwLck = lck;
        ///            _text = text ?? throw new ArgumentNu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestDeepIllegalWrapper {
            get {
                return ResourceManager.GetString("TestDeepIllegalWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.Vaults;
        ///using RwLck = DotNetVault.CustomVaultExamples.CustomLockedResources.StringBuilderRwLockedResource;
        ///using RoLck = DotNetVault.CustomVaultExamples.CustomLockedResources.StringBuilderRoLockedResource;
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public readonly ref struct FinalBadWrapper
        ///    {
        ///        public RwLck Lock =&gt; _rwLck;
        ///        public DateTime Stamp =&gt; _ts;
        ///        public string Text =&gt; _text ?? &quot;NONE&quot;;
        ///
        ///        internal FinalBadWrapper(in RwLck lck,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestDeepWrapperActuallyOk {
            get {
                return ResourceManager.GetString("TestDeepWrapperActuallyOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.TestCaseHelpers;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public class TestNdiOk
        ///    {
        ///        public static void TestNdiOkNoDirectInvoke()
        ///        {
        ///            using var chris = Name.CreateName(&quot;chris&quot;);
        ///            Console.WriteLine(chris.Text);
        ///        }
        ///
        ///        public static void TestAlsoOkNoDirectInvoke()
        ///        {
        ///            using (var chris = Name.CreateName(&quot;chris&quot;))
        ///            {
        ///                Console.WriteLine(chris.Text);
        ///            }
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestNdiOk {
            get {
                return ResourceManager.GetString("TestNdiOk", resourceCulture);
            }
        }
    }
}
