//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetVault.Test.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NdiTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NdiTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetVault.Test.ResourceFiles.NdiTestCases", typeof(NdiTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.TestCaseHelpers;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    static class NdiMixedWithNotInlineNotOkCaseThree
        ///    {
        ///        public static void NotOkNdiAndNotOkNotInlineTest()
        ///        {
        ///            Name chris;
        ///            using (chris = Name.CreateName(&quot;chris&quot;))
        ///            {
        ///                Console.WriteLine(chris.Text);
        ///            }
        ///            chris.Dispose();
        ///            Console.WriteLine(chris.Text);
        ///
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string NdiMixedWithNotInlineNotOkCaseThree {
            get {
                return ResourceManager.GetString("NdiMixedWithNotInlineNotOkCaseThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.TestCaseHelpers;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    static class NdiNotOkCaseOne
        ///    {
        ///        public static void NotOkNdiTest()
        ///        {
        ///            using var chris = Name.CreateName(&quot;chris&quot;);
        ///            chris.Dispose();
        ///            Console.WriteLine(chris.Text);
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string NdiNotOkCaseOne {
            get {
                return ResourceManager.GetString("NdiNotOkCaseOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.TestCaseHelpers;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    static class NdiNotOkCaseTwo
        ///    {
        ///        public static void NotOkNdiTest()
        ///        {
        ///            using (var chris = Name.CreateName(&quot;chris&quot;))
        ///            {
        ///                Console.WriteLine(chris.Text);
        ///                chris.Dispose();
        ///                Console.WriteLine(chris.Text);
        ///            }
        ///            
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string NdiNotOkTestTwo {
            get {
                return ResourceManager.GetString("NdiNotOkTestTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.TestCaseHelpers;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public class TestNdiOk
        ///    {
        ///        public static void TestNdiOkNoDirectInvoke()
        ///        {
        ///            using var chris = Name.CreateName(&quot;chris&quot;);
        ///            Console.WriteLine(chris.Text);
        ///        }
        ///
        ///        public static void TestAlsoOkNoDirectInvoke()
        ///        {
        ///            using (var chris = Name.CreateName(&quot;chris&quot;))
        ///            {
        ///                Console.WriteLine(chris.Text);
        ///            }
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestNdiOk {
            get {
                return ResourceManager.GetString("TestNdiOk", resourceCulture);
            }
        }
    }
}
