//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetVault.Test.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RefStructAttributeTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RefStructAttributeTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetVault.Test.ResourceFiles.RefStructAttributeTestCases", typeof(RefStructAttributeTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DotNetVault.Attributes;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public sealed class NotARefStruct
        ///    {
        ///        public override string ToString() =&gt; &quot;Hi mom!&quot;;
        ///    }
        ///
        ///    public struct AlsoNotARefStruct
        ///    {
        ///        public override string ToString() =&gt; &quot;Bye mom!&quot;;
        ///    }
        ///
        ///    public ref struct RefStructWithoutAttributeOk
        ///    {
        ///        public string Name { get; set; } 
        ///    }
        ///
        ///    public readonly ref struct RoRefStructWithoutAttributeOk
        ///    {
        ///        public string Name { get; }        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RefStructAttributeTestsOk {
            get {
                return ResourceManager.GetString("RefStructAttributeTestsOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DotNetVault.Attributes;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [RefStruct]
        ///    public struct RegularNotARefStruct
        ///    {
        ///        public string Name { get; set; }
        ///    }
        ///
        ///
        ///
        ///    //compiler takes care of this already
        ///    //[RefStruct]
        ///    //public sealed class Foobar
        ///    //{
        ///    //    public string Name { get; set; } = &quot;George&quot;;
        ///    //}
        ///
        ///    //[RefStruct]
        ///    //public enum Foobar
        ///    //{
        ///    //    Hi
        ///    //}
        ///    //[RefStruct]
        ///    //public interface IMDefinitelyNotARefStruct
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RefStructAttrNotOkCase1 {
            get {
                return ResourceManager.GetString("RefStructAttrNotOkCase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using DotNetVault.Attributes;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [RefStruct]
        ///    public readonly struct RoRegularNotARefStructCase2
        ///    {
        ///        public string Name { get; }
        ///
        ///        RoRegularNotARefStructCase2(string name) =&gt; Name = name ?? string.Empty;
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string RoRegularNotARefStructCase2 {
            get {
                return ResourceManager.GetString("RoRegularNotARefStructCase2", resourceCulture);
            }
        }
    }
}
