//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetVault.Test.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UsingMandatoryTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsingMandatoryTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetVault.Test.ResourceFiles.UsingMandatoryTestCases", typeof(UsingMandatoryTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.TestCaseHelpers;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public static class DiagnosticALittleMoreComplex
        ///    {
        ///        public static void TestMethod()
        ///        {
        ///            using (var disposable = new DisposableDooHickey())
        ///            {
        ///                Console.WriteLine(disposable.IsValid);
        ///                var shouldBeHereToo = MethodsWithAndWithoutUsingMandatoryAttribute.CreateDisposableRefStruct();
        ///                Console.WriteLine(shouldBeHereToo.IsValid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DiagnosticALittleMoreComplex {
            get {
                return ResourceManager.GetString("DiagnosticALittleMoreComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using DotNetVault.TestCaseHelpers;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    class EmitsDiagnosticUmRequiresInlineDecl
        ///    {
        ///        public static void EmitsDiagnosticNotDeclaredInline()
        ///        {
        ///            RefStructsRoxor disposeMe;
        ///            using (disposeMe =
        ///                MethodsWithAndWithoutUsingMandatoryAttribute.CreateDisposableRefStruct())
        ///            {
        ///                Console.WriteLine(disposeMe.IsValid);
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmitsDiagnosticUmRequiresInlineDecl {
            get {
                return ResourceManager.GetString("EmitsDiagnosticUmRequiresInlineDecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.TestCaseHelpers;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public static class NoDiagnosticALittleMoreComplex
        ///    {
        ///        public static void TestMethod()
        ///        {
        ///            var disposable = new DisposableDooHickey();
        ///            Console.WriteLine(disposable.IsValid);
        ///            using var shouldBeHereToo = MethodsWithAndWithoutUsingMandatoryAttribute.CreateDisposableRefStruct();
        ///            Console.WriteLine(shouldBeHereToo.IsValid &amp;&amp; !shouldBeHereToo.IsDis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoDiagnosticALittleMoreComplex {
            get {
                return ResourceManager.GetString("NoDiagnosticALittleMoreComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public static class NoDiagnosticPartOfUsingStatement
        ///    {
        ///        public static void GetUmMandatoryObject()
        ///        {
        ///            using (var disposeMe =
        ///                TestCaseHelpers.MethodsWithAndWithoutUsingMandatoryAttribute.CreateDisposableRefStruct())
        ///            {
        ///                Console.WriteLine(disposeMe.IsValid);
        ///            }
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string NoDiagnosticPartOfUsingStatement {
            get {
                return ResourceManager.GetString("NoDiagnosticPartOfUsingStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public static class Test
        ///    {
        ///        public static void GetUmMandatoryObject()
        ///        {
        ///            var disposeMe =
        ///                TestCaseHelpers.MethodsWithAndWithoutUsingMandatoryAttribute.CreateDisposableRefStruct();
        ///            Console.WriteLine(disposeMe.IsValid);
        ///        }
        ///    }
        ///    
        ///}
        ///.
        /// </summary>
        internal static string ShouldTriggerDiagnosticBecauseNoUsing {
            get {
                return ResourceManager.GetString("ShouldTriggerDiagnosticBecauseNoUsing", resourceCulture);
            }
        }
    }
}
