//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetVault.Test.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VaultSafeTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VaultSafeTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetVault.Test.ResourceFiles.VaultSafeTestCases", typeof(VaultSafeTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using AnalyzerYetAgain.Attributes;
        ///using JetBrains.Annotations;
        ///
        ///// ReSharper disable All
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    //No diagnostic: type is vault-safe
        ///    [VaultSafe]
        ///    public sealed class Cat
        ///    {
        ///        public int Age { get; }
        ///
        ///        public string Name { get; }
        ///
        ///        public Cat([NotNull] string name, int age)
        ///        {
        ///            if (name == null) throw new ArgumentNullException(nameof(name));
        ///            if (string.IsNullOrWhiteSpace(name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoDiagnosticAttributeYetCompliantCat {
            get {
                return ResourceManager.GetString("NoDiagnosticAttributeYetCompliantCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Text;
        ///using AnalyzerYetAgain.Attributes;
        ///// ReSharper disable All
        ///
        ///namespace DotNetVault.Test.TestCases 
        ///{
        ///    [VaultSafe(5*4&lt;21)]  
        ///    public sealed class NoDiagnosticBecauseOnFaith 
        ///    {
        ///        public StringBuilder MyStringBuilder { get; set; } = new StringBuilder();
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string NoDiagnosticBecauseOnFaith {
            get {
                return ResourceManager.GetString("NoDiagnosticBecauseOnFaith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ReSharper disable All
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public sealed class NoDiagnosticNoAttribute
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string NoDiagnosticNoAttribute {
            get {
                return ResourceManager.GetString("NoDiagnosticNoAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using AnalyzerYetAgain.Attributes;
        /////  /ReSharper disable All
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [VaultSafe(1 + 1 == 3)]
        ///    public class ShouldTriggerDiagnosticNotSealedAndVsAttribute
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string ShouldTriggerDiagnosticLowercaseAndVsAttributeV2 {
            get {
                return ResourceManager.GetString("ShouldTriggerDiagnosticLowercaseAndVsAttributeV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using AnalyzerYetAgain.Attributes;
        /////  /ReSharper disable All
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [VaultSafe(false)]
        ///    public class ShouldTriggerDiagnosticNotSealedAndVsAttribute
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string ShouldTriggerDiagnosticLowercaseAndVsAttributeV3 {
            get {
                return ResourceManager.GetString("ShouldTriggerDiagnosticLowercaseAndVsAttributeV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using AnalyzerYetAgain.Attributes;
        /////  /ReSharper disable All
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [VaultSafe]
        ///    public class ShouldTriggerDiagnosticNotSealedAndVsAttribute
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string ShouldTriggerDiagnosticNotSealedAndVsAttribute {
            get {
                return ResourceManager.GetString("ShouldTriggerDiagnosticNotSealedAndVsAttribute", resourceCulture);
            }
        }
    }
}
