//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetVault.Test.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VaultSafeTypeParamTypeTestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VaultSafeTypeParamTypeTestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetVault.Test.ResourceFiles.VaultSafeTypeParamTypeTestCases", typeof(VaultSafeTypeParamTypeTestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using AnalyzerYetAgain.Attributes;
        ///using AnalyzerYetAgain.LockedResources;
        ///
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [NoNonVsCapture]
        ///    public delegate TResult LocalQuery&lt;TInput, [VaultSafeTypeParam] TResult&gt;(in TInput input);
        ///
        ///    [NoNonVsCapture]
        ///    public delegate TResult LocalQuery&lt;TInput, [VaultSafeTypeParam] TAncillary, [VaultSafeTypeParam] TResult&gt;(
        ///        in TInput input, in TAncillary ancillary);
        ///    class [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DelegateCreationOpsAndDynamic {
            get {
                return ResourceManager.GetString("DelegateCreationOpsAndDynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Diagnostics;
        ///using System.Text;
        ///using AnalyzerYetAgain.Attributes;
        ///using AnalyzerYetAgain.Miscellaneous;
        ///
        ///// ReSharper disable LocalizableElement
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    class MethodInvokeSyntaxTests
        ///    {
        ///        public static Random RGen
        ///        {
        ///            get
        ///            {
        ///                if (!TheRandomGen.IsSet)
        ///                {
        ///                    TheRandomGen.SetNewValue(new Random((int)DateTime.Now.Ticks));
        ///                }
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodInvokeSyntaxTests {
            get {
                return ResourceManager.GetString("MethodInvokeSyntaxTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Diagnostics;
        ///using System.Text;
        ///using AnalyzerYetAgain.Attributes;
        ///using AnalyzerYetAgain.Miscellaneous;
        ///// ReSharper disable LocalizableElement
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///
        ///    class MethodInvokeSyntaxTests
        ///    {
        ///        public static Random RGen
        ///        {
        ///            get
        ///            {
        ///                if (!TheRandomGen.IsSet)
        ///                {
        ///                    TheRandomGen.SetNewValue(new Random((int) DateTime.Now.Ticks));
        ///                }        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodInvokeSyntaxTests_2 {
            get {
                return ResourceManager.GetString("MethodInvokeSyntaxTests_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using AnalyzerYetAgain.Attributes;
        ///using AnalyzerYetAgain.LockedResources;
        ///using JetBrains.Annotations;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    [NoNonVsCapture]
        ///    public delegate TResult LocalQuery&lt;TInput, [VaultSafeTypeParam] TResult&gt;(in TInput input);
        ///
        ///    [NoNonVsCapture]
        ///    public delegate TResult LocalQuery&lt;TInput, [VaultSafeTypeParam] TAncillary, [VaultSafeTypeParam] TResult&gt;(
        ///        in TInput input, in TAnci [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestDynamicNeverConsideredVaultSafe {
            get {
                return ResourceManager.GetString("TestDynamicNeverConsideredVaultSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using AnalyzerYetAgain.Attributes;
        ///using JetBrains.Annotations;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public sealed class VsTpObjectCreationExpDiag&lt;[VaultSafeTypeParam] T&gt;
        ///    {
        ///        public VsTpObjectCreationExpDiag([NotNull] T newV)
        ///        {
        ///            if (newV == null) throw new ArgumentNullException(nameof(newV));
        ///            _val = newV;
        ///        }
        ///
        ///        public override string ToString() =&gt; _val.ToString [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VsTpObjectCreationExpDiag {
            get {
                return ResourceManager.GetString("VsTpObjectCreationExpDiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using AnalyzerYetAgain.Attributes;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public interface IVsTpTypeOwner&lt;[VaultSafeTypeParam] T&gt;
        ///    {
        ///        Type TypeInfo { get; }
        ///    }
        ///
        ///    public class VsTpTypeOwner&lt;[VaultSafeTypeParam] T&gt; : IVsTpTypeOwner&lt;T&gt;
        ///    {
        ///        public Type TypeInfo =&gt; typeof(T);
        ///    }
        ///
        ///    public class JustOneVsTypeOwner&lt;TNotVaultSafe, [VaultSafeTypeParam] TVaultSafe&gt; : IVsTpTypeOwner&lt;TVaultSafe&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VsTpTypeHaver {
            get {
                return ResourceManager.GetString("VsTpTypeHaver", resourceCulture);
            }
        }
    }
}
