//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetVault.Test.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WhiteListTests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WhiteListTests() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetVault.Test.ResourceFiles.WhiteListTests", typeof(WhiteListTests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Text;
        ///using DotNetVault.Attributes;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public sealed class Holder&lt;[VaultSafeTypeParam] T&gt;
        ///    {
        ///        public T Value { get; }
        ///
        ///        public Holder(T addMe) =&gt; Value = addMe;
        ///    }
        ///
        ///    public static class TestWhiteListedVaultSafety
        ///    {
        ///        public static void TestMe()
        ///        {
        ///            Holder&lt;UriBuilder&gt; hb = new Holder&lt;UriBuilder&gt;(new UriBuilder(&quot;http://www.google.com&quot;));
        ///            Holder&lt;StringBuilder&gt; sb  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SbAndUriBNotVaultSafe {
            get {
                return ResourceManager.GetString("SbAndUriBNotVaultSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using DotNetVault.Attributes;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public sealed class Holder&lt;[VaultSafeTypeParam] T&gt;
        ///    {
        ///        public T Value { get; }
        ///
        ///        public Holder(T addMe) =&gt; Value = addMe;
        ///    }
        ///
        ///    public static class TestWhiteListedVaultSafety
        ///    {
        ///        public static void TestMe()
        ///        {
        ///            Holder&lt;System.Uri&gt; hb = new Holder&lt;System.Uri&gt;(new System.Uri(&quot;http://www.google.com&quot;));
        ///            Console.WriteLine(hb.Value);
        ///        }
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestUriWhiteListedVaultSafety {
            get {
                return ResourceManager.GetString("TestUriWhiteListedVaultSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        /////using System.Text;
        ///using DotNetVault.Attributes;
        ///
        ///namespace DotNetVault.Test.TestCases
        ///{
        ///    public sealed class Holder&lt;[VaultSafeTypeParam] T&gt;
        ///    {
        ///        public T Value { get; }
        ///
        ///        public Holder(T addMe) =&gt; Value = addMe;
        ///    }
        ///
        ///    public static class TestWhiteListedVaultSafety
        ///    {
        ///        public static void TestMe()
        ///        {
        ///            Holder&lt;string&gt; hb = new Holder&lt;string&gt;(&quot;Hi mom&quot;);
        ///            //Holder&lt;StringBuilder&gt; hb = new Holder&lt;StringBuilder&gt;(new Str [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestWhiteListedVaultSafety {
            get {
                return ResourceManager.GetString("TestWhiteListedVaultSafety", resourceCulture);
            }
        }
    }
}
